include:
  - ./base.yml
targets:
  {{cookiecutter.projectName}}Staging:
    templates:
      - Core

    settings:
      INFOPLIST_FILE: App/Project/staging/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.{{cookiecutter.projectName}}Staging
